apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: httpd
spec:
  containers:
    - name: container1
      image: httpd
      ports:
        - containerPort: 80
          protocol: TCP
