apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  # expose the application outside the cluster
  type: NodePort

  # select the pods to balance the load
  selector:
    app: httpd

  # configure the incoming and outgoing ports
  ports:
    # user will send the request to port 8001 of this service
    - port: 8001

      # service will send the request to the pods on port 80
      targetPort: 80
