apiVersion: v1
kind: Pod
metadata:
  name: httpd2
  labels:
    app: httpd
spec:
  containers:
    - name: httpd-container
      image: httpd
      ports:
        - containerPort: 80
          protocol: TCP
