- name: stop and remove apache
  hosts: servers
  become: yes
  tasks:
    - name: stop apache2
      service:
        name: apache2
        state: stopped

    - name: remove apache2
      apt:
        name: apache2
        state: absent
        purge: yes
