apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: container1
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP
