apiVersion: v1
kind: Pod
metadata:
  name: dummy
spec:
  containers:
    - name: container1
      image: httpd
      ports:
        - containerPort: 80
      env:
        - name: MY_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: BACKEND_URL

        - name: MY_PARAM1
          valueFrom:
            configMapKeyRef:
              name: myconfig
              key: PARAM1
