# select right base image

# set the /src as working directory of image

# copy everything from current directory of local machine 
# to working directory of image

# expose the right port

# install all the dependencies using `npm install` command

# run the server in container using `node server.js`