apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  # default type
  type: ClusterIP

  selector:
    # make sure the label here matches with label configured in deployment
    app: httpd
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
